import React from "react";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

// Components
import AppBar from "@/components/AppBar";
import AppFooter from "../components/AppFooter";
import AppSidebar from "@/components/AppSidebar";

// Global styles
import "../assets/styles/globals.scss";

// Our App's metadata, used for SEO and injected into the <head>
export const metadata = {
  title: "Next.js Clients App",
  description: "Generated by Next.js"
};

// The root layout for our app
export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body>
        <div id="App" className={"relative flex min-h-screen"}>
          <AppSidebar />
          <div className={"app flex flex-col w-full"}>
            <AppBar />
            <main className={"flex-grow p-10 bg-gray-100"}>
              {children}
            </main>
            <AppFooter />
          </div>
        </div>
      </body>
    </html>
  );
}
